### ISSUE TITLE
pip install encoding issue in setup.py on Windows

### ISSUE THREAD

**Issue by phizeroth** [emulbreh/pyffx#6]
Minor issue, `pip install pyffx` fails in Windows environment. Cloning from github and running setup.py worked fine.

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\phi\AppData\Local\Temp\pip-install-wohp0tb6\pyffx\setup.py", line 6, in <module>
        description = f.read()
      File "c:\users\phi\appdata\local\programs\python\python36-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 368: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\phi\AppData\Local\Temp\pip-install-wohp0tb6\pyffx\
```

**Comment by Elfrania** [comment]
I have the same problem too, and it shows up in pycharm. Will this be resolved soon?

**Comment by emulbreh** [comment]
I just released 0.3, which should contain a fix for this issue. Please reopen if you still have unicode issues.

**Comment by Elfrania** [comment]
Hi, I still can't used pycharm with pyffx (even in Mac). Has this been tested to be resolved?

**Comment by emulbreh** [comment]
@Elfrania can you share a traceback and your Python version?

**Comment by Elfrania** [comment]
python3
pycharm ananconda cannot locate pyffx.
